### ISSUE TITLE
Wazuh Dashboard first steps

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-dashboard#1]
## Wazuh dashboard

This repository forks the OpenSearch Dashboards repository to introduce changes that will ease its usage by Wazuh users and integrate itself with the Wazuh development process.

We want to accommodate our UX changes within the upstream code, minimizing conflicts. We want to contribute bug fixes and any component not tied to Wazuh upstream.

Also, we need to check all standard (vanilla) plugins are compatible with our builds, or we will need to build the infrastructure to build them ourselves too.

## To do

Our release branch will be based on OpenSearch Dashboards 2.4.1 and upwards. 

- Repository maintenance
  - [x] #2
  - [x] #43
  - [x] #10
- Infrastructure / CI pipelines
  - [x] #21
  - [x] #11
  - [x] Define build process
  - [x] #58 
- Introduce Wazuh changes
   - [x] #36 
       - [x] #38 
       - [x] #34 
   - [x] #15
   - [x] #37 
   - [x] #16
   - [x] #17
   - [x] #18
   - [x] #19
   - [x] #25
   - [x] #26
 - Test the development cycle 
   - [x] #46

**Comment by AlexRuiz7** [comment]
To keep this repository up-to-date with the original OpenSearch Repository, we need to periodically sync the fork bringing here (fork) the new changes made in the original repository (upstream).

For that, we'll follow the strategy defined in this [article](https://stefanbauer.me/articles/how-to-keep-your-git-fork-up-to-date). To minimize the conflicts between the repos, we'll use the rebase strategy, replaying our work on top of OpenSearch Dashboards features.

**Comment by hieu-ht** [comment]
Hello Wazuh Team!
I want to ask whether the version of Wazuh dashboard at this docker image `wazuh/wazuh-dashboard:4.3.11-dev` is using code from this repo or using Kibana with plugin `(Wazuh-kibana-app)`[https://github.com/wazuh/wazuh-kibana-app]?
Thanks!

**Comment by gdiazlo** [comment]
@hieu-ht it uses the code from wazuh-kibana-app and a standard binary distribution of opensearch. Our plan is to generate our own version of opensearch-dashboards from this repository in the coming weeks. 

Initially, the changes we're going to introduce here are the ones we're applying to the standard distribution in our packaging pipeline.

**Comment by AlexRuiz7** [comment]
URL of the OpenSearch Security plugin: https://repo1.maven.org/maven2/org/opensearch/plugin/opensearch-security/2.4.1.0/opensearch-security-2.4.1.0.zip
