### ISSUE TITLE
SAML authentication provider button on Dashboard

### ISSUE THREAD

**Issue by wolfjudge** [wazuh/wazuh-dashboard#102]
Hello community,

I have implemented SAML authentication for Wazuh Cluster. SAML provider is RC devs WebADM, I followed Okta documentation to make it work. ([link](https://documentation.wazuh.com/current/user-manual/user-administration/single-sign-on/administrator/okta.html))

After implementation, I dont get Wazuh frontend page anymore, I get redirected to provider page immediately and I can login with success. No issues there.

Question is, is there a way to get a button on Wazuh login page that can redirect me to my SAML provider, so I can preserve local login also. Now, if I want to login locally, I need to disable SAML first by commenting these lines

`opensearch_security.auth.type: "saml"
server.xsrf.allowlist: ["/_opendistro/_security/saml/acs", "/_opendistro/_security/saml/logout", "/_opendistro/_security/saml/acs/idpinitiated"]`

**Comment by gdiazlo** [comment]
Since Wazuh 4.4 you can enable that functionality configuring `/etc/wazuh-dashboards/opensearch_dashboards.yml` like:

```
opensearch_security.auth.type: ["basicauth","saml"]
opensearch_security.auth.multiple_auth_enabled: true
```

Please take a look at: 

https://opensearch.org/docs/2.6/security/configuration/multi-auth/

Wazuh 4.4 is based on OpenSearch 2.6 which has this configuration available.

**Comment by wolfjudge** [comment]
thank you very much @gdiazlo 
I did not look at opensearch documentation
Works
