### ISSUE TITLE
Compatibility with OpenSearch 2.10.0

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-dashboard#104]
## Description
We need to ensure the UI compatibility with the next version of OpenSearch v2.10.0
This update is still being discussed, but we need to be aware of potential issues.

## Functional requirements

- Review opensearch and opensearch-dashboard latest stable changelog. 
- Identify improvements and potential impact on the UI.
- Create new tracking and development branches.
- Develop a testing environment to verify our components would work under this new build.

## Plan

- [x] Apply Wazuh changes to OS 2.10 https://github.com/wazuh/wazuh-dashboard/tree/wz-4.8
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/5955
- [x] https://github.com/wazuh/wazuh-documentation/issues/6567

**Comment by yenienserrano** [comment]
We have seen that there are differences between OSD 2.9.0 and 2.10.0, in styles and also in other things like for example a new discover where the old discover will disappear in 2.11.0.

![image](https://github.com/wazuh/wazuh-dashboard/assets/63758389/6282075d-8da9-415a-846d-212e13b78863)
![image](https://github.com/wazuh/wazuh-dashboard/assets/63758389/d4f7734c-d378-453f-9f7d-c7a28573c6a3)
![image](https://github.com/wazuh/wazuh-dashboard/assets/63758389/62c2e96f-3de5-4b66-a474-e957ef61502a)
