### ISSUE TITLE
Build packages using GitHub Actions

### ISSUE THREAD

**Issue by Tostti** [wazuh/wazuh-dashboard#11]
## Description
The original repository contains several GitHub actions, with different processes that may allow us to build packages. This issue aims to track our investigation and testing process of those actions.

**Comment by Tostti** [comment]
Action `Manual build` is on the repo. It creates 2 different build for Linux, that are no tested yet.

**Comment by Tostti** [comment]
The action builds were tested and works as expected. 

I modified the logo and confirmed that the action takes into account the changes done to the repo
![imagen](https://user-images.githubusercontent.com/42900763/212698110-6d929804-3565-46f4-89c7-e1c7a22d56e1.png)

**Comment by Tostti** [comment]
The action is working as expected, generating a linux package on each run.

**Comment by AlexRuiz7** [comment]
Re-opened to add the changes using a pull request.
