### ISSUE TITLE
Generate branch 4.9.0

### ISSUE THREAD

**Issue by Tostti** [wazuh/wazuh-dashboard#118]
## Description
The fork will start being implemented in Wazuh 4.9.0. 
We need to generate the corresponding branch based on OpenSearch Dashboards 2.11.0 with all the previously applied changes.

### Pre-release
- [x] Create branch 4.9.0 based on OSD 2.11.0
- [x] Apply the changes that were previously applied to the branches
- [x] Bump version to 4.9.0
  - [x] If it is a bump version of Wazuh, update the test snapshot `src/core/server/rendering/rendering_service.test.ts`

**Comment by yenienserrano** [comment]
`wz-4.9` branch was created with the changes waiting for `4.9.0` branch with Opensearch Dashboards`2.11.0`
