### ISSUE TITLE
[BUG] The "Edit as Query DSL" functionality is generating both bad and incorrect DSL

### ISSUE THREAD

**Issue by JTMosaic** [wazuh/wazuh-dashboard#127]
The "Edit as Query DSL" functionality is generating both bad and incorrect DSL

**To Reproduce**

1. Log into Wazuh Dashboard and go to Security Events
2. Add a rule where rule.level is one of 3,4 or 5
![image](https://github.com/wazuh/wazuh-dashboard/assets/9417720/ba30629c-421d-456e-b2a3-f9b173af7cc2)
3. Edit the query and click on the Edit Query as DSL link to see:
 ```{
  "query": {
    "bool": {
      "should": [
        {
          "match_phrase": {
            "rule.level": "3"
          }
        },
        {
          "match_phrase": {
            "rule.level": "4"
          }
        },
        {
          "match_phrase": {
            "rule.level": "5"
          }
        }
      ],
      "minimum_should_match": 1
    }
  }
}
```
4. Click Cancel, edit the filter again and change the Operator to **_is not one of_** and save the query
5. Edit the query and click on the Edit Query as DSL link to see:
```{
  "query": {
    "bool": {
      "should": [
        {
          "match_phrase": {
            "rule.level": "3"
          }
        },
        {
          "match_phrase": {
            "rule.level": "4"
          }
        },
        {
          "match_phrase": {
            "rule.level": "5"
          }
        }
      ],
      "minimum_should_match": 1
    }
  }
}
```
This is the **_exact_** same DSL. The negation of the operator is not present.

Additionally, if you copy this DSL into a new filter you get a filter which is not editable as filter values and does not display correctly on the dashboard though it does seem to work, albeit without the NOT:

![image](https://github.com/wazuh/wazuh-dashboard/assets/9417720/e9e10893-fdf4-4d49-b7bd-8b06aecea6e0)

**Expected behavior**
Correct DSL should be generated to make queries easier to save and document

**OpenSearch Version**
wazuh-indexer 4.7.0-1

**Dashboards Version**
wazuh-dashboards 4.7.0-1

**Plugins**
Amazon AWS

**Comment by AlexRuiz7** [comment]
Hello @JTMosaic 

I've been doing some tests and, although it looks confusing, the DSL query is correct. First, let's check that `one of` and `not one of` yield different results:

`one of`
![image](https://github.com/wazuh/wazuh-dashboard/assets/15186973/ed2f12e6-9db2-4536-ba28-03a8074d7e78)


`NOT one of`
![image](https://github.com/wazuh/wazuh-dashboard/assets/15186973/5e8bcf71-6b9d-40a1-b7ba-f3107ed5c510)


As you can see, even if the DSL query is the same, the results are different, meaning the filters are being applied correctly. Let's take a deeper look at it by studying the actual queries:

`one of`
```json
{
  "bool": {
    "must": [],
    "filter": [
      {
        "match_all": {}
      },
      {
        "match_phrase": {
          "manager.name": {
            "query": "redacted.com"
          }
        }
      },
      {
        "bool": {
          "should": [
            {
              "match_phrase": {
                "rule.level": "3"
              }
            },
            {
              "match_phrase": {
                "rule.level": "4"
              }
            },
            {
              "match_phrase": {
                "rule.level": "5"
              }
            }
          ],
          "minimum_should_match": 1
        }
      },
      {
        "range": {
          "timestamp": {
            "gte": "2023-12-17T11:37:27.954Z",
            "lte": "2023-12-18T11:37:27.954Z",
            "format": "strict_date_optional_time"
          }
        }
      }
    ],
    "should": [],
    "must_not": []
  }
}
```


`NOT one of`
```json
{
  "bool": {
    "must": [],
    "filter": [
      {
        "match_all": {}
      },
      {
        "match_phrase": {
          "manager.name": {
            "query": "redacted.com"
          }
        }
      },
      {
        "bool": {
          "should": [
            {
              "match_phrase": {
                "rule.level": "3"
              }
            },
            {
              "match_phrase": {
                "rule.level": "4"
              }
            },
            {
              "match_phrase": {
                "rule.level": "5"
              }
            }
          ],
          "minimum_should_match": 1
        }
      },
      {
        "range": {
          "timestamp": {
            "gte": "2023-12-17T11:37:27.954Z",
            "lte": "2023-12-18T11:37:27.954Z",
            "format": "strict_date_optional_time"
          }
        }
      }
    ],
    "should": [],
    "must_not": []
  }
}
```


As you can see, the only difference on the query is in which category the filter is applied to: `must`, `filter`, `should` or `must_not`. The filter itself is the same. This is how the [BOOLEAN query](https://opensearch.org/docs/latest/query-dsl/compound/bool/) works.


It's a problem of scope, as the general query can't be seen in the DSL query JSON editor, it only works within the current filter's scope.

If you still believe this is a bug, please, open an issue on https://github.com/opensearch-project/OpenSearch-Dashboards/issues, as they are the original authors of the component.

Regards,
Alex

**Comment by JTMosaic** [comment]
Thanks for your effort, Alex. Strangely, I am not seeing the same DSL as you are even though I believe I am creating the same filters. I'd like to understand if this is an OpenSearch issue or a Wazuh issue before I go and open an issue with OpenSearch. 

I am on Wazuh 4.7.0 running on Linux using Firefox or Chrome to access the WebUI

My DSL does not contain the word **must** but instead contains the word **should**. Any idea why that may be? When I create a filter I can only add one Field at a time and it appears to be added as an "OR" (should) rather than and "AND" (must). Can you tell me how you set up your filters so I can see if my DSL produces the **must** directive?

Also, the two DSL you posted in your reply are, in fact, identical. The must_not section isn't populated. I'm not understanding the difference you are explaining about context. From what U read on [https://opensearch.org/docs/latest/query-dsl/compound/bool/](url) the must_not section should be populated to get a NOT result. From the example DSL on that page: 
![image](https://github.com/wazuh/wazuh-dashboard/assets/9417720/9c185498-2735-45e6-b066-1f9bab92f7bc)


What I am looking for is a way to use the DSL as a backup to save our filters for documentation and for reapplication after upgrades which have, in the past, removed our defined filters.

**Comment by AlexRuiz7** [comment]
You are right @JTMosaic. I copied the same JSON twice, my bad. It's now fixed.


I'm creating the filters as seen in this image:

![image](https://github.com/wazuh/wazuh-dashboard/assets/15186973/f0b21a68-3392-4bed-a9cb-2dc52e1b68c2)

**Comment by JTMosaic** [comment]
Thanks, Alex. I think you may be creating your filters in a manner differently than I am. For example, I cannot see more than one filter in the DSL at a time while your DSL seems to show three separate filters (manager_name, date range, and rule level).

When I have these filters in place: 

![image](https://github.com/wazuh/wazuh-dashboard/assets/9417720/7382e6d4-ff9c-4dbe-a940-43ac2c11dd7d)

I can only see the DSL for the rule.level filter and, again, it doesn't show the NOT in the DSL and uses "should" instead of "must" or "must_not". In fact, if I create the filter as "is not one of" and then edit the DSL to change "should" to "must not" I get this:

![image](https://github.com/wazuh/wazuh-dashboard/assets/9417720/e030d522-c037-4849-82bb-a1adbf127919)

which essentially negates the NOT from the filter and the "must_not" in the DSL and logically turns them into "should"

Would you share step-by-step instructions on how you created your filter with the DSL above? Also, are you using any non-standard or developer settings?

**Comment by AlexRuiz7** [comment]
The JSON shared in my previous [comment](https://github.com/wazuh/wazuh-dashboard/issues/127#issuecomment-1860271289) is extracted from the actual query sent to the Indexer. I got it using the browser's dev tools.

I didn't explicitly mention that before, maybe that's causing confusion. My apologies for that.
![image](https://github.com/wazuh/wazuh-dashboard/assets/15186973/9c60fc82-82d7-4733-9e65-af96e6b778b1)

**Comment by JTMosaic** [comment]
@AlexRuiz7 Thanks for explaining that. However, that is outside of the UI and outside of the normal usage of the app which is what I was asking about. Sure, I could do what you have demonstrated but why should I _have_ to? Shouldn't the UI provide this capability? Shouldn't the UI provide the correct DSL without having to dig into the source for the webpage?

Also, I opened this case with the statement that the "Edit as Query DSL" was generating bad and incorrect DSL, which it is, if you use the UI.

What is actually going on under the covers is different from what is shown in the UI, as you have clearly demonstrated, and that is what I was asking to have considered as a bug.

Even were I to take the filter request and paste it as DSL, which will work, it creates a filter which then cannot be edited using the "filter values" interface. 

That is, this filter:

![image](https://github.com/wazuh/wazuh-dashboard/assets/9417720/128d97fd-9bc1-4576-9a1a-a4abd4e72d6e)

Shows this DSL in the UI:

```
{
  "query": {
    "bool": {
      "should": [
        {
          "match_phrase": {
            "rule.level": "3"
          }
        },
        {
          "match_phrase": {
            "rule.level": "4"
          }
        },
        {
          "match_phrase": {
            "rule.level": "5"
          }
        }
      ],
      "minimum_should_match": 1
    }
  }
}
```

But **actually** creates this filter:

```
{
  "bool": {
    "must": [],
    "filter": [
      {
        "match_all": {}
      },
      {
        "match_phrase": {
          "manager.name": {
            "query": "roc-log.p.mosaicsg.net"
          }
        }
      },
      {
        "range": {
          "timestamp": {
            "gte": "2023-12-19T14:14:10.805Z",
            "lte": "2023-12-20T14:14:10.805Z",
            "format": "strict_date_optional_time"
          }
        }
      }
    ],
    "should": [],
    "must_not": [
      {
        "bool": {
          "should": [
            {
              "match_phrase": {
                "rule.level": "3"
              }
            },
            {
              "match_phrase": {
                "rule.level": "4"
              }
            },
            {
              "match_phrase": {
                "rule.level": "5"
              }
            }
          ],
          "minimum_should_match": 1
        }
      }
    ]
  }
}
```

I see you point about the NOT being applied at the context level by encapsulating the "should" **_inside_** of a "must_not" but that should show up in the DSL in the UI. 

My complaint was about the UI, not about the functionality. 

The "Edit as Query DSL" is not working as expected and impacts the portability and documentation utility of queries using DSL. As of right now, there is no good way to backup or document saved queries and DSL should be it.

**Comment by AlexRuiz7** [comment]
Hi @JTMosaic 

All I can say is that I agree with you there. The "Edit as Query DSL" button has an inappropriate scope, and should show the final result of the filter, otherwise is misleading, as we have proven. However, this UI component is inherited from OpenSearch Dashboards, and fixing that on our side would result in an inconsistent behavior among the different plugins installed in the platform. We also lack the design and implementation details about this component and its interfaces yet to perform such a change.

For these reasons, I encourage you to transfer this issue to [OpenSearch Dashboards](https://github.com/opensearch-project/OpenSearch-Dashboards). Let's see what are their thoughts on this. You can for sure link this issue to theirs for better context and comprehension of the problem.

Best regards,
Alex

**Comment by JTMosaic** [comment]
Thanks, Alex. I'll try and do that

**Comment by Tostti** [comment]
I'm closing this issue as it is on OpensSearch's side. 

In https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5649 they added the label `2.13.0`, so it will possibly be fixed for that version of OpenSearch. 
In future versions of Wazuh, we will use that (or higher) version of OpenSearch, and will also be fixed in Wazuh Indexer. 

Feel free to open a new issue in case that you need it. 

Regards,
