### ISSUE TITLE
Discover section is empty

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-dashboard#135]
**Describe the bug**

During https://github.com/wazuh/wazuh/issues/21318 for 4.8.0-alpha2 it was detected that the Discover section shows no data when no filters are added. Also no information is shown as filters are added either.

**To Reproduce**
1. Go to 'Discover section'
2. See error no alerts or data is shown
3. Try to filter alerts by agent.id -> No options are shown or accepted

**Expected behavior**
Discover section shows all alerts on all agents and allows filtering.

**Screenshots**

- 4.7.2
![image](https://github.com/wazuh/wazuh-dashboard/assets/14501079/f24c3296-84ae-4e4c-8366-1518cf806064)

- v4.8.0-alpha2
![image](https://github.com/wazuh/wazuh/assets/14501079/571a2476-64c1-4b10-92fe-e8d1492b25bf)

**Comment by gdiazlo** [comment]
We could not reproduce it. The second capture does not show any mapped field. It could be related to the test environment. We do not have enough information to debug this problem.
