### ISSUE TITLE
Move the script to setup the configuration to bin directory

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-dashboard#142]
# Description

A script that allows to migrate the configuration from a `wazuh.yml` file was added to the for now to the `wazuh-core` but we think due to the funcionality this should be related to the platform instead, so we want to to move to the `bin` directory of the production Wazuh dashboard

Related comment: https://github.com/wazuh/wazuh-dashboard-plugins/issues/6201#issuecomment-1931935700

**Comment by asteriscos** [comment]
The will not be implemented, because we rolled back the stateless configuration changes.
