### ISSUE TITLE
Support new Wazuh version 5.0.0 in `wazuh-dashboard` repository

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-dashboard#145]
## Description

This issue attempts to support a new version 5.0.0 in the `wazuh-dashboard` repository

## Tasks

- [x] Create numbered branch for current `master` version (`4.9.0`) using `master` branch on `wazuh-dashboard` repository.
- [x] https://github.com/wazuh/wazuh-dashboard/pull/148

**Comment by lucianogorza** [comment]
LGTM

**Comment by Tostti** [comment]
All tasks successfully completed
