### ISSUE TITLE
[BUG] Data table visualization applies wrong filter when sorted

### ISSUE THREAD

**Issue by medtemo** [wazuh/wazuh-dashboard#146]
**Describe the bug**
If you sort a data table by one of its columns and then filter for a value using the + button on a cell, it applies the filter with the original value on that cell instead of the current one

**To Reproduce**

    Create a data table visualization
    Click on 'Sort asc' or 'sort desc' on a table column header
    Click on the + button on a cell to filter for that value
    The value on the filter is different from the one on the cell

**Expected behavior**
The filter should use the value that is currently displayed on the cell.

**OpenSearch Version**
The one packaged with the wazuh-indexer v4.7.2

**Dashboards Version**
v4.7.2

**Plugins**
n/a

**Screenshots**

**Host/Environment (please complete the following information):**

    OS: Ubuntu 22
    Browser and version: Different Browsers

**Additional context**
Maybe this is related https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4836

**Comment by Tostti** [comment]
Hi @medtemo, apologies for the late response. 
This problem was related to the issue that you linked. It was fixed in OpenSearch 2.11, meaning that it will be on Wazuh 4.9.0 (that uses OpenSearch 2.13)
