### ISSUE TITLE
Compatibility with OpenSearch v2.12.0

### ISSUE THREAD

**Issue by yenienserrano** [wazuh/wazuh-dashboard#149]
## Description
We need to ensure the UI compatibility with the next version of OpenSearch v2.12.0
This update is still being discussed, but we need to be aware of potential issues.

For that, we need to:

- [x] Review opensearch and opensearch-dashboard latest stable changelog. 
- [x] Identify improvements and potential impact on the UI.
- [x] Create new tracking and development branches.
- [x] Develop a testing environment to verify our components would work under this new build.

## Issues
-  _List here the detected issues_

**Comment by yenienserrano** [comment]
## [OpenSearch Dashboards 2.11.0 Release Notes](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/release-notes/opensearch-dashboards.release-notes-2.12.0.md)
> [Discover] Revert to legacy discover table and add toggle to new discover table  (https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5789)
> [Discover] Add collapsible and resizeable sidebar (https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5789)
> [Discover] Update fonts of the datagrid (https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5841)

**Comment by yenienserrano** [comment]
The discover legacy revert will still give us the error in the data-explore console, maybe deleting discover old, wazuh we won't get the error.

![image](https://github.com/wazuh/wazuh-dashboard/assets/63758389/1a967081-20a7-4b18-b70b-7a78337d9368)

**Comment by yenienserrano** [comment]
When navigating between dashboard and events 3 times, the visualizations are empty

![image](https://github.com/wazuh/wazuh-dashboard/assets/63758389/de0e7c53-a61d-4cb0-8d7e-b7b196a5d9e9)

**Comment by yenienserrano** [comment]
When optimizing, the code warns us that some things will be deprecated from the `wazuh-dashboard-plugins` repository.


![image](https://github.com/wazuh/wazuh-dashboard/assets/63758389/b86c7df3-cafe-41ea-865c-7f5590a24f17)

**Comment by yenienserrano** [comment]
packages are created correctly and the tar package works as expected

![image](https://github.com/wazuh/wazuh-dashboard/assets/63758389/24643f3d-10f9-449a-9373-274b86c3071b)

![image](https://github.com/wazuh/wazuh-dashboard/assets/63758389/c446bd0a-cc5d-490d-a1ce-7e0b55f6e6d3)

**Comment by yenienserrano** [comment]
## rpm

rpm package works correctly 
```console
[root@localhost opensearch]# cat  /etc/os-release
NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream 9"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:centos:centos:9"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
```
![image](https://github.com/wazuh/wazuh-dashboard/assets/63758389/5d3582eb-0a88-408b-9af1-e3f2c3a58352)

**Comment by Tostti** [comment]
All tasks completed. Renamed the new branch to `4.9.0`, and the previous branch to `4.9.0-2.11.1`. Changed the enviroment variable to `2.12.0`. 

LGTM
