### ISSUE TITLE
Vulnerability detector module not showing any events after initial scan

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh-dashboard#155]
**Describe the bug**

The Vulnerability Detection module is not showing any alerts in the **Events** tab after the baseline scan. 

According to the team, this is expected because the baseline scan goes to the `wazuh-states-vulnerabilities` index (used in **Dashboard** and **Inventory**) and the vulnerability detector alerts go to `wazuh-events-*` indices (used in **Events**).

However, I do think we should consider including the alerts generated in the initial scan in the list to be consistent with the ones generated by the vulnerability detector on subsequent scans.

**To Reproduce**

1. Setup an all-in-one manager
2. Add a linux agent
3. Go to the **Vulnerability Detection** module
4. See the alerts generated
5. Go to the **Events** tab
6. See `"No results match your search criteria"` message

**Expected behavior**
The **Events** tab shows the list of events generated during the baseline scan.

**Screenshots**

<details><summary>Images</summary>

![ubuntu_2](https://github.com/wazuh/wazuh-dashboard/assets/51374959/44fce3ed-948d-4637-9dc6-d83514f74096)
![ubuntu_3](https://github.com/wazuh/wazuh-dashboard/assets/51374959/94eeb099-456e-4f7b-b920-e08edddd93cc)
![ubuntu_4](https://github.com/wazuh/wazuh-dashboard/assets/51374959/99d734b8-850f-40c0-ab28-5b304319f5cd)

</details>

**Host/Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser and version [e.g. 22]: Firefox 121.0.1

**Comment by sebasfalcone** [comment]
This is not an issue with the dashboard, the change is related to the expected behaviour of the new VD ([see comment](https://github.com/wazuh/wazuh/issues/22455#issuecomment-2003480313))
