### ISSUE TITLE
[BUG] Darkmode not dark

### ISSUE THREAD

**Issue by SHoover80** [wazuh/wazuh-dashboard#159]
**Describe the bug**

Dark mode is enabled, But the onlything showing dark is the background. I've clear'd the history/cache, I've tried another browser, even another computer, I've restarted the device running wazuh yet this is all I'm currently getting when I go into darkmode. 

**To Reproduce**
1. Go to 'darkmode, and only the background goes dark'

**Expected behavior**
to go into darkmode, 

**OpenSearch Version**
everything is latest, Fresh install. 

**Dashboards Version**
everything is the latest, I litterly installed about 15 minutes ago then ran a update. 

**Plugins**

Freshinstall, nothing has been added, changed or setup. I installed, logged in, and attemted to change to darkmode

**Screenshots**
![image](https://github.com/wazuh/wazuh-dashboard/assets/43644167/98f6f9dc-bb3f-4787-9129-45cc8cfdddaa)

![image](https://github.com/wazuh/wazuh-dashboard/assets/43644167/6dc4c97b-898e-40ea-8563-d0cb349b81dc)

**Host/Environment (please complete the following information):**
 - OS: [Ubuntu]
 - Browser and version [Chrome is up to date
Version 123.0.6312.86 (Official Build) (64-bit)]

**Additional context**

**Comment by SHoover80** [comment]
And yes, I did try to toggle the darkmode setting.

**Comment by SHoover80** [comment]
I narrowed it down to something with using Nginx proxy manager. When I go directly to the host IP:Port darkmode works.

**Comment by Tostti** [comment]
I'm closing this issue as the problem has been reported to be related to the use of an external tool and not to the Wazuh Dashboard itself.

**Comment by nicokempe** [comment]
> I narrowed it down to something with using Nginx proxy manager. When I go directly to the host IP:Port darkmode works.

Hi @WhiskeySheppard, we are facing the same issue and also using the NGINX Proxy Manager, did you find a solution for this problem?

**Comment by nicokempe** [comment]
> I narrowed it down to something with using Nginx proxy manager. When I go directly to the host IP:Port darkmode works.

Hi @WhiskeySheppard, we just faced the same problem and were able to resolve it by just disabling the "Cache Assets" option on in the NGINX Proxy Manager settings. Maybe you or other people that are facing this issue too in the future can be supported with this insight:

![Image](https://github.com/user-attachments/assets/5fe62608-b634-4aa0-9395-eeb03ca68be2)
