### ISSUE TITLE
Replace documentation links with Wazuh's

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-dashboard#18]
## Description

We would like to show the Wazuh's version in the Help menu instead of the version of OpenSearch Dashboards.

Help menu in OpenSearch Dashboards:
![image](https://user-images.githubusercontent.com/15186973/217779319-565ed83b-163f-4122-b920-833f2d279c74.png)

Help menu in Wazuh Dashboard:
![image](https://user-images.githubusercontent.com/15186973/217778769-e1905f40-d6f4-4d22-952b-0371473faa39.png)

The number shown there is the value of the variable `opensearchDashboardsVersion`, which is equal to `version` in the `package.json` file. This won't be a major problem unless it must match the version of the indexer nodes. At least the minor version must match, for example, 2.4.0 in dashboards and 2.4.1 in indexer works, so we cannot simply change this value in the `package.json`. We'll need to add a new field to this field, for example `wazuhVersion`, in which we can set the Wazuh version this platform is built for, and read this value in the React component instead of the original `opensearchDashboardsVersion` variable.

All the related tests must be updated too, and probably we'll need to create new code to read this new value from the `package.json` and transport it to the required component.

After that, we can define and dynamically generate our documentation links using this value, and use them in the Help menu. 

The documentation links are centralized in DocLinksService:
https://github.com/wazuh/wazuh-dashboard/blob/e5c52ac0621ae76602560beaf36536162116ccf8/src/core/public/doc_links/doc_links_service.ts#L39-L77

**Comment by AlexRuiz7** [comment]
I found a bug during production that prevents the app from working.

The Wazuh version defined in the `package.json` file isn't read as the `package.json` is a different, minimal, version generated during the building process.

**Comment by yenienserrano** [comment]
Re-opened in https://github.com/wazuh/wazuh-dashboard/pull/55

See https://github.com/wazuh/wazuh-dashboard/issues/1#issuecomment-1516555068 for details.
