### ISSUE TITLE
Document the generation of `wazuh-dashboard` packages

### ISSUE THREAD

**Issue by Tostti** [wazuh/wazuh-dashboard#182]
# Description
We need to document how to generate `wazuh-dashboard` packages as an official documentation page.

**Comment by yenienserrano** [comment]
The `dockerfile` is almost finished to create an image that facilitates the process of building all the packages and the generation of the base package with everything integrated in `tar` format, according to the specified branches of each repository.

After creating the base package(s) to generate the unified base they can be extracted from the container with the command `docker cp <container name>:</home/node/packages/. or /home/node/wzd/dev-tools/build-packages/base/output/.> <path where you want to copy them>`.

with the unified package if you wish you can create the `deb` and `rpm` packages by running their respective scripts. 

It remains to update the pr documentation to the documentation repository with this new information and polish a little more if necessary the `dockerfile`.

**Comment by rauldpm** [comment]
Pull request closed, please check https://github.com/wazuh/wazuh-documentation/pull/7328#issuecomment-2141833100
