### ISSUE TITLE
[BUG] Session timeout with SAML

### ISSUE THREAD

**Issue by dlundgren** [wazuh/wazuh-dashboard#193]
**Describe the bug**
We are seeing the same issues as described in https://github.com/opensearch-project/security-dashboards-plugin/issues/828 and there appears to be a fix for the session issues https://github.com/opensearch-project/security-dashboards-plugin/pull/1773.

**Expected behavior**
Sessions should behave better than currently do, or bounce to the SAML login. Right now we get a 500 error and have to manually clear the cookies, as we can't visit the /auth/logout url, as we still get the 500 error.

**OpenSearch Version**
wazuh-dashboard 4.7.4 (opensearch 2.8.0 based on jar files)

**Host/Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser and version: Firefox 126.0.1

**Comment by Tostti** [comment]
Hi @dlundgren, apologies for the late response. 
I see that the fix in OpenSearch is for their 2.12 version. This will be available from Wazuh 4.9.0, based on OpenSerach 2.13.

Regards,
