### ISSUE TITLE
Possibility to easily update agents via GUI

### ISSUE THREAD

**Issue by mvdberge** [wazuh/wazuh-dashboard#196]
**Is your feature request related to a problem? Please describe.**

After you implemented the update checker (thanks! :raised_hands:) it's a logical next step to 
1. inform the user when an agent is outdated
2. provide a function to directly remote-update that/all agent(s) 

**Describe the solution you'd like**

1. Add a logic to check for outdated agents
2. Show the outdated agents, maybe directly in the agent overview table and on the individual agent tab
![grafik](https://github.com/wazuh/wazuh-dashboard/assets/8587894/c5435b8a-e04b-4a13-a23d-30067cf4fdae)
3. Provide a button to directly remote-update that agent
4. Maybe provide a button to mass-update all outdated agents

**Describe alternatives you've considered**

I wrote a very simple bash script to remote-update all agents at once, maybe that explains what I'm wishing to be included in the GUI.

```
#!/bin/bash
outdated_agents=$(/var/ossec/bin/agent_upgrade -l|awk '/^[0-9]+/ {print $1}')
for agent in ${outdated_agents}
do
    echo "Updating agent ${agent}"
    /var/ossec/bin/agent_upgrade -a ${agent}
done
```

**Comment by LuXc-NL** [comment]
+1

**Comment by Tostti** [comment]
Hi, apologies for the late response. 

The feature will be added in version 4.9.0, which will be released soon.

You can see more information in 
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6496
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6253
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6512
