### ISSUE TITLE
Create `docker-compose` development environment

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-dashboard#21]
## Description

To develop, we need a development environment. We have need to create a development environment for the Wazuh Dashboard app to run, tests and build the source code of the app and the [security plugin](https://github.com/wazuh/wazuh-security-dashboards-plugin).

We'll follow the same approach as in our Wazuh Kibana app environments.

### Tasks

- [x] Create a docker compose environment, following our Docker strategy

## Considerations

- Create the `docker` folder and add the new files there (scripts, configuration files, ...).

**Comment by yenienserrano** [comment]
Re-opened in #52 

See https://github.com/wazuh/wazuh-dashboard/issues/1#issuecomment-1516555068 for details.
