### ISSUE TITLE
Wazuh dashboard's help window has a whitespace between `v` and `version`

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-dashboard#225]
# Description

Testing the Step-by-Step deployment in the https://github.com/wazuh/wazuh-dashboard/issues/223 issue, I have found an error in the Wazuh dashboard version's help window

There is an extra whitespace between `v` and `version`, which is not present in previous versions

![image](https://github.com/wazuh/wazuh-dashboard/assets/14913942/501d4f78-cef8-4238-a3c2-20dd1777de77)
![image](https://github.com/wazuh/wazuh-dashboard/assets/14913942/86dca828-84a5-460c-b314-f0f6b4e3045d)

In the pre-4.9.0 versions, this is being modified in

https://github.com/wazuh/wazuh-packages/blob/master/stack/dashboard/base/builder.sh#L140C1-L140C209

```console
sed -i 's|"core.ui.chrome.headerGlobalNav.helpMenuVersion",defaultMessage:"v {version}"|"core.ui.chrome.headerGlobalNav.helpMenuVersion",defaultMessage:"v'${version}'"|' ./src/core/target/public/core.entry.js
```

## Related

- https://github.com/wazuh/wazuh-packages/pull/1512

# Tasks

- [ ] Remove whitespace

**Comment by gdiazlo** [comment]
To me that looks an unintended change in the sed command which was in charge of setting the version. As the new code does modify it in the forked version, the unintended change disappeared.

**Comment by gdiazlo** [comment]
We will use the opensearch style to avoid creating more conflicting changes and possible style problems.
