### ISSUE TITLE
Create default config files for Wazuh

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-dashboard#26]
## Description

We need to create the default configuration files for Wazuh. More precisely, the `opensearch_dashboards.yml` file.

Also, some of the base changes were applied directly to the source code, and later had to be reverted due to tests not passing. These changes will be applied using the corresponding configuration options.

## Changes
- [x] #17 
- [x] `expandedHeader`

**Comment by yenienserrano** [comment]
Re-opened in https://github.com/wazuh/wazuh-dashboard/pull/53

See https://github.com/wazuh/wazuh-dashboard/issues/1#issuecomment-1516555068 for details.
