### ISSUE TITLE
Support new Wazuh version 4.8.2 in wazuh-dashboard repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-dashboard#267]
## Description

This issue attempts to support a new version 4.8.2 in the wazuh-dashboard repository.

## Tasks

~~- [ ] Bump 4.8.2 branch to 4.8.2 version on wazuh-dashboard repository, including revision and changelog.~~

> [!note]
> wazuh-security-dashboards-plugin will be implemented since 4.9.0

**Comment by Desvelao** [comment]
I will close the issue as not planned because this plugin will be used for Wazuh 4.9.0.
