### ISSUE TITLE
Generate final tag and publish draft release for Wazuh 4.8.2

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-dashboard#272]
## Description

This issue attempts to publish draft release and generate final tag for version 4.8.2 in the wazuh-dashboard repository.

## Tasks

- [ ] Generate final tag v4.8.2 from branch 4.8.2 on wazuh-dashboard repository.
- [ ] Publish [GitHub draft release](https://github.com/wazuh/wazuh-dashboard/releases) from [tag v4.8.2](https://github.com/wazuh/wazuh-dashboard/tree/v4.8.2).

**Comment by Desvelao** [comment]
I'm closing this issue as the repository will not be used until version 4.9.0
