### ISSUE TITLE
Change main Wazuh loading logo

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard#278]
# Description

We need to replace the current spinner `.gif` loading files for the SVG "loading" file used in Wazuh 4.8.x.

Example spinner:
https://github.com/wazuh/wazuh-dashboard/blob/4.9.1/src/core/server/core_app/assets/logos/spinner_on_light.gif

![Peek 2024-08-26 16-13](https://github.com/user-attachments/assets/f4aa451e-9389-4520-917d-803d588c9409)

**Comment by JuanGarriuz** [comment]
### Research

In this issue Wazuh loading logo was changed

- https://github.com/wazuh/wazuh-dashboard/pull/78/files#diff-75eae74d533696bb486805bdd71dfeb9b8628143dcebacb6a7a0bb1c53df92bb
