### ISSUE TITLE
Generate final tag and publish draft release for Wazuh 4.9.0

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-dashboard#289]
## Description

This issue attempts to publish draft release and generate final tag for version 4.9.0 in the wazuh-dashboard repository.

## Tasks

- [x] Generate final tag v4.9.0 from branch 4.9.0 on wazuh-dashboard repository.
  - https://github.com/wazuh/wazuh-dashboard/pull/291
- [x] Publish [GitHub draft release](https://github.com/wazuh/wazuh-dashboard/releases) from [tag v4.9.0](https://github.com/wazuh/wazuh-dashboard/tree/v4.9.0).

**Comment by Tostti** [comment]
LGTM
