### ISSUE TITLE
[BUG] Filter on dashboard  parameter (description, Groups, ID) not possible since fresh install 4.9.0

### ISSUE THREAD

**Issue by s23hck** [wazuh/wazuh-dashboard#312]
**Describe the bug**

Since a fresh install of all component in one liner ([link here](https://documentation.wazuh.com/current/quickstart.html#installing-wazuh)) i lost all dashboard filter available in older release.
For example in "Threat Hunting" dashboard : filter dashboard by "Description", "Groups", "agent.name" , etc was available with one click button by clicking on "+" or "-". This resulted in filter on this or to exclude this value ("Description", "Groups", "agent.name").
Even if i click on "inspect document details, i lost this button "+" or "-"

Also the sort possibility, eg by "rule.level" by clicking "sort Z to A" or "sort A to Z" do nothing
[EDIT] just seeing that, we must disable the "default" sorting by "timestamp" to sort correctly.

**To Reproduce**
1. Install https://documentation.wazuh.com/current/quickstart.html#installing-wazuh
2. Login to dashboard / Home / Overview / Threat Hunting
3. Scroll down to result table

**Expected behavior**
Have the ability to filter on each of the dashboard fields in one click : decoder.name, description, location, rule.groups, etc ..

**OpenSearch Version**
Sorry i don't know where to find it

**Dashboards Version**
Sorry i don't know where to find it, it's the latest stable version maybe v 4.9.0 (that's the version displayed in dashboard help)

**Plugins**

No extra plugin installed 

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: Ubuntu 22.04.5 LTS (fully update)
 - Browser and version : Firefox 123.0 (64-bit) and Chromium 128.0.6613.119 (64-bit)

**Comment by asteriscos** [comment]
Hi @s23hck, thank you for your feedback. We added the filtering feature in the data grid events table in Wazuh 4.9.1. We will also add the filtering feature in the document details flyout for 4.10.0.

- https://github.com/wazuh/wazuh-dashboard-plugins/issues/7080
