### ISSUE TITLE
Changing the language of the web dashboard

### ISSUE THREAD

**Issue by pouriiia** [wazuh/wazuh-dashboard#334]
Hello, I wanted to translate the web dashboard into several languages, is it possible?
If it is possible, please guide me how to access the texts and user interface of the web dashboard

**Comment by Santiago-Lorenzo** [comment]
We have the same question as well. Is there a way to set another language associated with the dashboard and enrich any language files it uses?

**Comment by uranus829** [comment]
@guidomodarelli Hello,Which version can support multiple languages? Thank you!

**Comment by guidomodarelli** [comment]
@uranus829 Hello, the upcoming major update will include support for multiple languages.

**Comment by oneil1838** [comment]
will be there also a language selection for the CIS check? e.g. in Windows 2025 in German the command "net.exe accounts" will answer in German, so the check always fails

**Comment by azurejoga** [comment]
We already have multi languages ​​in the new update?

**Comment by brlin-tw** [comment]
> will be there also a language selection for the CIS check? e.g. in Windows 2025 in German the command "net.exe accounts" will answer in German, so the check always fails

This is rather a bug in the CIS check as they should always run in the English locale.
