### ISSUE TITLE
[BUG]The Vulnerability Detection menu has been removed since Wazuh 4.9.

### ISSUE THREAD

**Issue by pyama86** [wazuh/wazuh-dashboard#335]
**Describe the bug**

![CleanShot 2024-10-02 at 15 01 55@2x](https://github.com/user-attachments/assets/b1d26294-0af9-49f7-9645-e45b18f1eb1f)

Before Wazuh 4.9, there was a link to the Vulnerability Detection screen in the capture section of each node, but it seems to be missing from version 4.9 onwards. However, since it is still available in the side menu, this could potentially be a mistake or an oversight in the interface changes introduced in 4.9.

**To Reproduce**

**Expected behavior**

**OpenSearch Version**
2.13.0

**Dashboards Version**
4.9.0

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by yenienserrano** [comment]
Hi @pyama86 I was checking and indeed it was a problem that had 4.9.0 and in the next versions was fixed, if you are still in that version and want to have the button you can upgrade to the latest version, currently 4.9.2
