### ISSUE TITLE
Integrate the reporting plugin in the package building process

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard#338]
# Description
As part of the MVP of the reporting revamp objective, we need to integrate the new Reporting plugin repository in the package building process. This involves changing the GitHub actions to include the new repository

#### Objective
- https://github.com/wazuh/wazuh-dashboard/issues/164

## Tasks
- [ ] Change GitHub actions to include the dashboard reporting plugin in the package building process.

**Comment by Desvelao** [comment]
Taking into account we are replacing a plugin and this needs to be built, I think we should update the documetation to build this plugin too.
