### ISSUE TITLE
Generate final tag and publish draft release for Wazuh 4.9.1

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-dashboard#359]
## Description

This issue attempts to publish draft release and generate final tag for version 4.9.1 in the wazuh-dashboard repository.

## Tasks

- [x] Generate final tag v4.9.1 from branch 4.9.1 on wazuh-dashboard repository.
- [x] Publish [GitHub draft release](https://github.com/wazuh/wazuh-dashboard/releases) from [tag v4.9.1](https://github.com/wazuh/wazuh-dashboard/tree/v4.9.1).

**Comment by Desvelao** [comment]
Fixed the GHA build references https://github.com/wazuh/wazuh-dashboard/pull/361.

Recreated tag and release.
