### ISSUE TITLE
Hide `overview` app and its links

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-dashboard#37]
## Description

We have been asked to hide the `overview` app.

Initially, this change was applied in #15, but this change as enough context to be treated as an independent work unit, hence this issue.

Port the changes from #22 to a new pull request.

**Comment by yenienserrano** [comment]
Re-opened in https://github.com/wazuh/wazuh-dashboard/pull/54

See https://github.com/wazuh/wazuh-dashboard/issues/1#issuecomment-1516555068 for details.
