### ISSUE TITLE
[BUG] Wazuh Endpoints - MITRE Something went wrong

### ISSUE THREAD

**Issue by DarrenRainey** [wazuh/wazuh-dashboard#437]
**Describe the bug**

**To Reproduce**
1. Go to Dashpoint > Server Management > Endpoint Summary > [Select any Endpoint] > MITRE ATT&CK Top Tatics
2. Click on any of the listed tatics (Clean windows install presents an tatic for defense evasion.
3. Click on any of the tatics
4. Get redirected to error page.

Clean wazuh install on Ubuntu 22.04 using quick start method
```
curl -sO https://packages.wazuh.com/4.9/wazuh-install.sh && sudo bash ./wazuh-install.sh -a
```

**Screenshots**

Screenshots attached:
![1](https://github.com/user-attachments/assets/6050ba28-fb87-44e8-b9d1-7220c71c5fa2)
![2](https://github.com/user-attachments/assets/0cb53deb-fed0-4478-bddd-5b6878cb5d56)
![3](https://github.com/user-attachments/assets/dccd8527-aa18-4e64-909c-86707f297b93)
![4](https://github.com/user-attachments/assets/82462bb6-d21c-422a-87c4-ac1f59384675)

**Host/Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Latest versions of Brave browser, Google chrome and Microsoft edge tested

**Comment by yenienserrano** [comment]
HI @DarrenRainey I was testing and indeed in 4.9.x we have this issue.

But I could see that we already had an issue with this and it is fixed here in next versions you will see it fixed.

Issue:
https://github.com/wazuh/wazuh-dashboard-plugins/issues/7064

PR:
https://github.com/wazuh/wazuh-dashboard-plugins/pull/7116
