### ISSUE TITLE
[BUG] Cannot read properties of undefined - Something went wrong

### ISSUE THREAD

**Issue by farrukh1991** [wazuh/wazuh-dashboard#455]
Hi,
On 4.9.2 i m facing the issue during clicking on MITRE ATT@&CK tab:

Failed on request [POST /utils/logs/ui] Error: 3021 - Cannot read properties of undefined (reading 'logger')
    at GenericRequest.request (wazuh.plugin.js:1:411459)
    at async error_orchestrator_ui_ErrorOrchestratorUI.storeError (wazuh.plugin.js:1:564623)

**Comment by farrukh1991** [comment]
Hi @yenienserrano,
I m running Wazuh on Oracle Linux 9.5. Installed from the official manual https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/installation-assistant.html..

If you need, we can have a quick call via zoom and i will show you the issue.

**Comment by farrukh1991** [comment]
During installation i see the following:

bash wazuh-install.sh --generate-config-files
24/12/2024 09:49:43 INFO: Starting Wazuh installation assistant. Wazuh version: 4.9.2
24/12/2024 09:49:43 INFO: Verbose logging redirected to /var/log/wazuh-install.log
24/12/2024 09:49:43 INFO: The recommended systems are: Red Hat Enterprise Linux 7, 8, 9; CentOS 7, 8; Amazon Linux 2; Ubuntu 16.04, 18.04, 20.04, 22.04.
24/12/2024 09:49:43 WARNING: The current system does not match with the list of recommended systems. The installation may not work properly.
24/12/2024 09:49:44 INFO: Verifying that your system meets the recommended minimum hardware requirements.

**Comment by farrukh1991** [comment]
![Image](https://github.com/user-attachments/assets/b9075db8-c385-4710-a83b-a7e0a3f4f2be)

![Image](https://github.com/user-attachments/assets/af0388d3-1939-4058-b134-1150a9aaa666)

**Comment by farrukh1991** [comment]
On Oracle Linux 7.9 the same error...

**Comment by yenienserrano** [comment]
HI @farrukh1991 I was testing and indeed in 4.9.x we have this issue.

But I could see that we already had an issue with this and it is fixed here in next versions you will see it fixed.

Issue:
https://github.com/wazuh/wazuh-dashboard-plugins/issues/7064

PR:
https://github.com/wazuh/wazuh-dashboard-plugins/pull/7116

**Comment by farrukh1991** [comment]
Hi @yenienserrano ,
When 4.10 will be released?

**Comment by yenienserrano** [comment]
We are currently in the release candidate phase, you can see it in the versions section on GitHub.

https://github.com/wazuh/wazuh-dashboard/releases

You can check the progress in the different weeks or wait for the announcement to be made.

**Comment by yenienserrano** [comment]
I close due to inactivity
