### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by RedstoneWizard08** [wazuh/wazuh-dashboard#70]
**Is your feature request related to a problem? Please describe.**

I would really like it if the Wazuh Dashboard had a dark mode, as dark modes are very nice :p

**Describe the solution you'd like**

I would just like the option to enable a dark mode inside of the dashboard config.

**Comment by AlexRuiz7** [comment]
Hello @RedstoneWizard08 

You can enable the dark mode in Stack Management < Advanced settings.

You'll be asked to reload the page. This mode will be enabled globally.

![image](https://github.com/wazuh/wazuh-dashboard/assets/15186973/e7151d13-2a65-416d-a99e-50769e8fbebe)

After reloading the page:

![image](https://github.com/wazuh/wazuh-dashboard/assets/15186973/80eaabeb-d5c8-4959-90ae-ad3482799094)

Let me know it this solves your request.

Regards,
Alex

**Comment by RedstoneWizard08** [comment]
That worked! Apparently I'm just blind. Thanks!
