### ISSUE TITLE
Test distribution packages

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-dashboard#72]
## Description

In this issue, we'll be testing the packages generated with the tools included in #71.

The objective is to test the building mechanism and check if we can provide the same [operating system compatibility](https://opensearch.org/docs/2.8/install-and-configure/install-opensearch/index/#operating-system-compatibility) as OpenSearch.

Attach the testing results (evidence) and the reproducibility (Vagrantfile, commands, ...) of the test below.

| OS                    | Version           |
|-----------------------|-------------------|
| RHEL/CentOS           | 7/8               |
| Rocky Linux/AlmaLinux | 8                 |
| Ubuntu                | 16.04/18.04/20.04 |
| Windows Server        | 2019              |

## Tests

During the tests, follow the [installation instructions](https://opensearch.org/docs/2.8/install-and-configure/install-dashboards/index/) from OpenSearch for the given operating system (package type).

- [x] Test RPM package in RHEL/CentOS 7/8 
- [x] Test RPM package in Rocky Linux/AlmaLinux 8
- [x] Test DEB package in Ubuntu 16.04/18.04/20.04
- [ ] Test TAR (Windows) package in Windows Server 2019
- [x] Test TAR (Linux) package in any of the supported operating systems*

*This test can be performed in Docker or locally, while others are preferred in VMs.

**Comment by AlexRuiz7** [comment]
## CentOS 8 (rpm)  🟢

https://files.slack.com/files-pri/TMYFNFQ3W-F05F642FP4Z/image.png

**Comment by AlexRuiz7** [comment]
## node:14.20.04 - dev environment (deb) 🟢 

![image](https://github.com/wazuh/wazuh-dashboard/assets/15186973/8f36422b-58ef-4868-bf63-9744ecb0fc7e)

![image](https://github.com/wazuh/wazuh-dashboard/assets/15186973/b638b520-4129-4a1b-bf95-d4eaf59b6b88)

![image](https://github.com/wazuh/wazuh-dashboard/assets/15186973/41dc5a85-715e-436d-861c-5ca562ef7b9a)

**Comment by Tostti** [comment]
## Ubuntu 18.04 (deb)  🟢
![image](https://github.com/wazuh/wazuh-dashboard/assets/42900763/7c355607-af54-4d73-874c-59127e68cea4)
![image](https://github.com/wazuh/wazuh-dashboard/assets/42900763/4f4a2aa7-2404-4600-befd-39d480a2d49b)

**Comment by Tostti** [comment]
## rockylinux 8 (rpm) 🟢 
![image](https://github.com/wazuh/wazuh-dashboard/assets/42900763/12e95e75-3724-4b1c-95ec-a7bff722c908)
![image](https://github.com/wazuh/wazuh-dashboard/assets/42900763/ad0ccb3c-9fa7-4cf1-bf93-b28a7641ce71)
![image](https://github.com/wazuh/wazuh-dashboard/assets/42900763/0d83de5c-582a-4d99-bbd1-cbe1b7f4ba4e)

**Comment by Desvelao** [comment]
# Ubuntu 16.04 (deb) g:reen_circle:

<details>
  <summary>Vagrantfile</summary>
  
  ```ruby
  # -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.hostname = "ubuntu16.04"
  config.vm.network "private_network", ip: "192.168.56.9"
  config.vm.provider "virtualbox" do |pmv|
    pmv.memory = 4082
    pmv.cpus = 2
    pmv.name = "Ubuntu16.04"
    pmv.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end
end
  ```
</details>

Operating system information
```console
root@ubuntu16:/vagrant# cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
![image](https://github.com/wazuh/wazuh-dashboard/assets/34042064/cbc03a37-0052-4d31-9e71-586f720ea31e)
![image](https://github.com/wazuh/wazuh-dashboard/assets/34042064/28505db5-c902-479b-befb-308f18d454f2)

**Comment by Desvelao** [comment]
# Bonus - Ubuntu 22.04 (deb) :green_circle:

<details>
  <summary>Vagrantfile</summary>
  
  ```ruby
  # -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.hostname = "ubuntu-2204"
  config.vm.network "private_network", ip: "192.168.56.9"
  config.vm.provider "virtualbox" do |pmv|
    pmv.memory = 4092
    pmv.cpus = 2
    pmv.name = "Ubuntu22.04"
    pmv.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end
end
  ```
</details>

Operating system information
```console
root@ubuntu-2204:/home/vagrant# cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

![image](https://github.com/wazuh/wazuh-dashboard/assets/34042064/d8481dcf-aa68-4182-a15f-87fc310d7774)
![image](https://github.com/wazuh/wazuh-dashboard/assets/34042064/cbb221c0-2730-4e7b-8f2d-6420a6f97249)

Remove package:
```console
root@ubuntu-2204:/home/vagrant# dpkg -r wazuh-dashboard
(Reading database ... 131206 files and directories currently installed.)
Removing wazuh-dashboard (4.4.0-1) ...
Stopping wazuh-dashboard service... OK
Deleting PID directory... OK
Deleting installation directory... OK
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...

Reinstalling package:
```console
root@ubuntu-2204:/home/vagrant# dpkg -i /vagrant/wazuh-dashboard_4.4.0-1_amd64.deb
Selecting previously unselected package wazuh-dashboard.
(Reading database ... 44477 files and directories currently installed.)
Preparing to unpack .../wazuh-dashboard_4.4.0-1_amd64.deb ...
Unpacking wazuh-dashboard (4.4.0-1) ...
Setting up wazuh-dashboard (4.4.0-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
```
```

**Comment by AlexRuiz7** [comment]
We drop Windows Server support as we encountered several [issues](https://github.com/opensearch-project/opensearch-build/issues/3700) to generate the packages, requires a builder and Wazuh didn't offer Windows support in previous versions.
