### ISSUE TITLE
[Solved] Cant' login to dashboard behind a reverse Proxy

### ISSUE THREAD

**Issue by r4a5a88** [wazuh/wazuh-dashboard#75]
I setup wazuh behind an apache reverse proxy

apache conf
```
<VirtualHost *:443>

         ServerName hostname
        <Directory /var/www/html/>
         Options -Indexes +Multiviews +FollowSymlinks
         </Directory>

         SSLEngine on
         SSLCertificateFile /etc/apache2/CERT
         SSLCertificateKeyFile /etc/apache2/KEY
      

         ProxyRequests off
         ProxyPreserveHost On
         ProxyVia full

                 RewriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R,L]

         RewriteCond %{HTTPS} off
         RewriteRule ^(.*)$ https://%{HTTP_HOST}%/$1 [L,R=301]


         ProxyPass / http://192.168.13.110/
         ProxyPassReverse / http://192.168.13.110/



 Alias /robots.txt /var/www/robots.txt
 <Location "/robots.txt">
    ProxyPass "!"
 </Location>
 </VirtualHost>

```
 opensearch.yml
```
server.port: 80
opensearch.ssl.verificationMode: certificate
# opensearch.username: kibanaserver
# opensearch.password: kibanaserver
opensearch.requestHeadersAllowlist: ["securitytenant","Authorization"]
opensearch_security.multitenancy.enabled: false
opensearch_security.readonly_mode.roles: ["kibana_read_only"]
server.ssl.enabled: false
server.ssl.key: "/etc/wazuh-dashboard/certs/dashboard-key.pem"
server.ssl.certificate: "/etc/wazuh-dashboard/certs/dashboard.pem"
opensearch.ssl.certificateAuthorities: ["/etc/wazuh-dashboard/certs/root-ca.pem"]
uiSettings.overrides.defaultRoute: /app/wazuh
opensearch_security.cookie.secure: true
server.host: 192.168.13.110
opensearch.hosts: https://192.168.13.110:9200
```
I was able to access the dashboard but I could not login with the admin user or the wazuh user

**Comment by jbiset** [comment]
Hi, @r4a5a88.

It appears to be a rewriterule problem. In your current Apache configuration, you have:

```
RewriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R,L]

RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%/$1 [L,R=301]
```

Please try one of the following alternatives:

**- Alternative 1:**
```
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI}
```

**- Alternative 2:**
```
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}$1 [L,R=301]
```

**- Alternative 3:**
```
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}/$1 [L,R=301]
```

Here is the Wazuh documentation link that can be used, even for Splunk reverse-proxy: https://documentation.wazuh.com/current/deployment-options/splunk/splunk-reverse-proxy.html

If none of the alternatives work, you can check and add more information such as the following:

- List of devtools network requests (useful to activate the option to preserve the log)
- Check Apache logs at:
`/var/log/apache2/access.log`
`/var/log/apache2/error.log`
- Check the Wazuh Dashboard logs:
`journalctl -u wazuh-dashboard`
`cat /var/log/messages | grep -i "wazuh-dashboard"`

**Comment by r4a5a88** [comment]
I changed it to alternative 1 and still can't login . Do I have to install splunk for a reverse proxy system to work. can't the dashboard do it on its own?
 
![555](https://github.com/wazuh/wazuh-dashboard/assets/22817846/6e8ea2ab-3849-4059-a483-452f2821ec7d)

**Comment by jbiset** [comment]
No need to install splunk. But maybe could help since it also mentions how to install with reverse proxy. 
Alternative 3 seems the most correct to me.
You can check and add more information such as the following?
- List of devtools network requests (useful to activate the option to preserve the log)
- Check Apache logs at:
/var/log/apache2/access.log
/var/log/apache2/error.log
- Check the Wazuh Dashboard logs:
journalctl -u wazuh-dashboard
cat /var/log/messages | grep -i "wazuh-dashboard"

**Comment by r4a5a88** [comment]
I solved it. Thank for the advie with the apache error log . there was another site interfering with wazuh
